### ISSUE TITLE
the trait bound `Cognito: Transform<<impl actix_service::ServiceFactory<ServiceRequest> as actix_service::ServiceFactory<ServiceRequest>>::Service, ServiceRequest>` is not satisfied

### ISSUE THREAD

**Issue by k-bx** [robertohuertasm/actix-web-middleware-cognito#3]
Not familiar enough with relevant traits, getting this error when trying to integrate actix-web-middleware-cognito:

```
error[E0277]: the trait bound `Cognito: Transform<<impl actix_service::ServiceFactory<ServiceRequest> as actix_service::ServiceFactory<ServiceRequest>>::Service, ServiceRequest>` is not satisfied
   --> src/server/mod.rs:902:19
    |
902 |             .wrap(cognito)
    |                   ^^^^^^^ the trait `Transform<<impl actix_service::ServiceFactory<ServiceRequest> as actix_service::ServiceFactory<ServiceRequest>>::Service, ServiceRequest>` is not implemented for `Cognito`

error: aborting due to previous error
```

actix-web: v4.0.0-beta.5

**Comment by robertohuertasm** [comment]
This is because you're using actix-web beta. They introduced breaking changes. If I have time I'll prepare a beta release too but I can promise you when that will be. :(

**Comment by robertohuertasm** [comment]
@k-bx I've just published a new version supporting actix-web 4.0.0-beta.5: https://crates.io/crates/actix-web-middleware-cognito/0.4.0-beta.5

**Comment by k-bx** [comment]
Thank you!

**Comment by robertohuertasm** [comment]
If you ever need to use beta.6,  you can get it [here](https://github.com/robertohuertasm/actix-web-middleware-cognito/tree/v0.4.0-beta.6)
